### ISSUE TITLE
Time spent scanning numbers blows up in very large files

### ISSUE THREAD

**Issue by rianadon** [alufers/openscad-parser#23]
I have an issue that is very much an edge case in your parser, since it only affects really big files.

My use case is parsing CSG of [keycaps](https://github.com/pseudoku/PseudoMakeMeKeyCapProfiles) I've passed through OpenSCAD in order to run the boolean operations myself, since the WASM build of OpenSCAD is pretty slow. Your parser has been working excellently with these files, since the CSG is just a subset of SCAD code. However, the files can also get pretty massive.

One file in particular has a polyhedrons of ~7000 vertices each, and I attached one such polygon here: [big_poly.txt](https://github.com/alufers/openscad-parser/files/13847609/big_poly.txt) (I had to upload in txt format since GitHub doesn't let me upload scad). The problem is the code I'm using here takes forever to execute:

```typescript
const parser = require('openscad-parser')
const file = await parser.CodeFile.load('big_poly.scad')
parser.ParsingHelper.parseFile(file)
```

And a profile from `node --inspect`
<img width="1121" alt="Screenshot 2024-01-05 at 3 00 31 PM" src="https://github.com/alufers/openscad-parser/assets/18223213/234bfd61-c5da-44a4-a331-4743c02873c9">

The problem looks to be that the parser [is running a regular expression](https://github.com/alufers/openscad-parser/blob/f7fe9bc2de4e5d59677ee8f9d9d46bfba3d76ec8/src/Lexer.ts#L460) for scanning numbers over the entire source file every time it scans a token. I wonder if simply placing carets in front of the regular expressions would fix the issue (since you enforce `match.index == 0`), or maybe there's a way to do the scanning without requiring regular expressions? 500 milliseconds to scan a single token is pretty long.

**Comment by alufers** [comment]
Huh, this indeed seems pathological. I will try to look into it.

**Comment by alufers** [comment]
As you said, adding a `^` fixed the issue. Parsing the file now takes ~130ms instead of 9s on my machine.

**Comment by rianadon** [comment]
Thanks for taking a look into this and making a new release already :) I'm glad it was a simple fix.
