### ISSUE TITLE
x=[for([0:3]) 1] throws a Syntax Error but OpenSCAD says it's valid

### ISSUE THREAD

**Issue by paulftw** [alufers/openscad-parser#27]
I ran into this problem while trying to parse [vacuum-hose-adapter-openscad.scad#L1074](https://github.com/ostat/vacuum-hose-adapter-openscad/blob/main/combined/vacuum-hose-adapter-openscad.scad#L1074)

### Steps to reproduce

OpenSCAD accepts following code:
```
x = [for([0:3]) 1];
echo(x);
```

> ECHO: [1, 1, 1, 1]

But `openscad-parser` reports a syntax error.

`x = [for([0:3]) 1];` and `x = [for(FOO=[0:3]) 1];` seem to produce the same result in OpenSCAD

**Comment by alufers** [comment]
Fixed in 0.6.1
