### ISSUE TITLE
Trailing comments when using multiple operators can break parsing

### ISSUE THREAD

**Issue by easytarget** [alufers/openscad-parser#29]
If there are multiple operators on a single line before an action, and if this line ends with a comment, it breaks parsing of the following action line.
* I'm finding hard to explain.. so an example should show what I mean.

`$ cat ex.scad`
```
$fn=4;// a comment
translate([-5,-5,-10]) scale([1,1,2]) // another comment
cube([10,10,10]);
```
Note the second line has a translate, then a scale, then a comment. This is a valid syntax and OpenSCAD accepts and renders it without complaint.

When parsed the result is not valid SCAD.
`$ ./openscad-parser/node_modules/.bin/scadfmt ex.scad`
```
$fn = 4; // a comment
translate([-5, -5, -10]) 
    scale([1, 1, 2]) 
    // another commentcube([10, 10, 10]);
```

**Comment by alufers** [comment]
Fixed in 0.6.2

Thank you for the report
